[package]
name = "rust-gan"
description = "A demo of Rust interop with Python, using advanced packages like PyTorch with Nix deployment."
authors = ["Artemis Rosman <rozukke@proton.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.2", features = ["auto-initialize"] }